###########################
##     Docker Compose    ##
##                       ##
###########################
version: '2'
services:
  app:
    build: .
    image: kinesic
    ports:
      - "8000"
    volumes:
      - .:/usr/src/app/
      - ./logs/kinesic:/var/log/kinesic
      - static_files:/usr/src/app/static
    links:
      - postgres
    environment:
      - DB_DEFAULT_HOST=${DB_DEFAULT_HOST}
      - DB_DEFAULT_PORT=${DB_DEFAULT_PORT}
      - DB_DEFAULT_USER=${DB_DEFAULT_USER}
      - DB_DEFAULT_PASSWORD=${DB_DEFAULT_PASSWORD}
      - DB_DEFAULT_NAME=${DB_DEFAULT_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  nginx:
    build: ./nginx
    image: nginx
    ports:
      - "80:9000"
    links:
      - app
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files:/usr/src/app/static:ro

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_DEFAULT_USER}
      - POSTGRES_PASSWORD=${DB_DEFAULT_PASSWORD}
      - POSTGRES_DB=${DB_DEFAULT_NAME}

volumes:
  static_files: {}