# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title and venue')),
                ('description', models.TextField(null=True, verbose_name='Long description')),
                ('date', models.DateTimeField(verbose_name='Date of the event')),
                ('tickets_info', models.URLField(null=True, verbose_name='Link to buy tickets')),
            ],
        ),
    ]
