# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gallery Photo')),
                ('image', models.ImageField(upload_to=b'gallery_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'gallery photo',
                'verbose_name_plural': 'gallery photos',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_info',
            field=models.URLField(blank=True, verbose_name='Link to buy tickets'),
        ),
    ]
